services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      DB_HOST: postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      DB_HOST: postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM: admin@app.test
      MAILER_FROM_NAME: admin
      FRONTEND_URL: http://localhost
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

volumes:
  postgres:
