services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    environment:
      APP_DEBUG: 1
      APP_ENV: dev

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app

  node:
    build:
      context: docker/node
    volumes:
      - ./:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
